{
    "name": "MASAR Brand",
    "version": "19.0.1.0.0",
    "summary": "MASAR company branding, bilingual AR/EN defaults, and website readiness",
    "category": "Hidden",
    "author": "MASAR",
    "website": "https://masar.sa",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "contacts",
        "crm",
        "sale_management",
        "account",
        "project",
        "hr",
        "calendar",
        "website",
        "website_crm",
        "mass_mailing",
        "board",
    ],
    "data": [
        "data/res_company_data.xml",
        "data/ir_config_parameter_data.xml",
        "data/website_data.xml",
    ],
    "assets": {},
    "installable": true,
    "application": false,
    "auto_install": false,
}
