{
    "name": "MASAR Brand",
    "version": "19.0.1.1.0",
    "summary": "MASAR dark website theme, solutions cards, and company branding",
    "category": "Website",
    "author": "MASAR",
    "website": "https://masar.sa",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "contacts",
        "crm",
        "sale_management",
        "account",
        "project",
        "hr",
        "calendar",
        "website",
        "website_crm",
        "mass_mailing",
        "board",
    ],
    "data": [
        "data/res_company_data.xml",
        "data/ir_config_parameter_data.xml",
        "data/website_data.xml",
        "views/website_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "masar_brand/static/src/scss/masar_website.scss",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}
